import { business, services } from './content.js';

const nav = `<nav aria-label="Primary"><a href="/laser-cutting/">Laser cutting</a><a href="/metal-fabrication/">Fabrication</a><a href="/cnc-folding/">CNC folding</a><a href="/welding/">Welding</a><a href="/granulator-screens/">Screens</a><a href="/about/">About</a></nav>`;
const escapeJson = value => JSON.stringify(value).replace(/</g, '\\u003c');

export function layout({ title, description, path = '/', body, robots = 'noindex,nofollow' }) {
  const canonical = `${process.env.SITE_URL || 'http://localhost:3000'}${path}`;
  const schema = {'@context':'https://schema.org','@type':['LocalBusiness','Organization'],name:business.name,url:canonical,telephone:'+441142422733',email:business.email,address:{'@type':'PostalAddress',streetAddress:'4 Colwall Street',addressLocality:'Sheffield',postalCode:'S9 3WP',addressCountry:'GB'}};
  return `<!doctype html><html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="${robots}"><title>${title}</title><meta name="description" content="${description}"><link rel="canonical" href="${canonical}"><meta property="og:title" content="${title}"><meta property="og:description" content="${description}"><meta property="og:type" content="website"><meta property="og:url" content="${canonical}"><meta property="og:image" content="${process.env.SITE_URL || 'http://localhost:3000'}/og-image.svg"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/favicon.svg"><link rel="manifest" href="/site.webmanifest"><link rel="stylesheet" href="/site.css"><script type="application/ld+json">${escapeJson(schema)}</script><script src="/site.js" defer></script></head><body><a class="skip" href="#main">Skip to content</a><header class="header"><a class="brand" href="/" aria-label="Parkway Fabrications home"><span>PF</span><strong>PARKWAY<br>FABRICATIONS</strong></a><button class="menu" aria-expanded="false" aria-controls="nav-wrap">Menu</button><div id="nav-wrap">${nav}<a class="button button--small" href="/request-a-quote/">Request a quote</a></div></header><main id="main">${body}</main>${footer()}<div data-whatsapp hidden></div></body></html>`;
}

function footer(){return `<footer><div><p class="eyebrow">Start a conversation</p><h2>Bring the drawing.<br><em>We’ll discuss the route.</em></h2><a class="button" href="/request-a-quote/">Request a quote</a></div><div class="footer-grid"><address>${business.name}<br>${business.address.join('<br>')}</address><p><a href="${business.phoneHref}" data-event="phone_clicked">${business.phone}</a><br><a href="mailto:${business.email}" data-event="email_clicked">${business.email}</a></p><p><a href="/privacy-policy/">Privacy</a><br><a href="/terms/">Terms</a></p></div><p class="fine">© ${new Date().getFullYear()} Parkway Fabrications. Development preview — not for indexing.</p></footer>`}

const serviceLinks = Object.entries(services).map(([url,s],i)=>`<a class="service-card" href="${url}"><span>0${i+1}</span><h3>${s.title.replace(' Sheffield','')}</h3><p>${s.description}</p><b>Explore capability →</b></a>`).join('');

export function home(){return layout({title:'Parkway Fabrications | Laser Cutting & Metal Fabrication Sheffield',description:'Laser cutting, CNC folding, welding and bespoke metal fabrication in Sheffield. Send your drawing to discuss a connected manufacturing route.',body:`<section class="hero"><div class="hero-copy"><p class="eyebrow">Sheffield · South Yorkshire</p><h1><span>Precision fabrication.</span><em>Built in Sheffield.</em></h1><p class="lede">From drawing to finished fabrication: laser cutting, CNC folding, welding and bespoke manufacturing coordinated under one roof.</p><div class="actions"><a class="button" href="/request-a-quote/">Request a quote</a><a class="text-link" href="/request-a-quote/#upload">Upload a drawing →</a></div><ul class="capabilities"><li>Laser cutting</li><li>CNC folding</li><li>Welding</li><li>Bespoke fabrication</li></ul></div><div class="laser" aria-hidden="true"><div class="machine"><span></span></div><svg viewBox="0 0 700 520"><defs><linearGradient id="steel"><stop stop-color="#23282d"/><stop offset="1" stop-color="#090b0e"/></linearGradient><filter id="glow"><feGaussianBlur stdDeviation="7"/></filter></defs><path class="plate" d="M90 130 610 78 660 403 138 458Z"/><path class="cut glow" d="M215 330 245 190 420 175 526 286 480 350 310 365Z"/><path class="cut" d="M215 330 245 190 420 175 526 286 480 350 310 365Z"/><circle class="beam" cx="215" cy="330" r="7"/></svg><p>Drawing <b>→</b> Cut <b>→</b> Fold <b>→</b> Weld <b>→</b> Finish</p></div></section><section class="statement"><p class="eyebrow">One connected workflow</p><h2>Less hand-off.<br><em>More control.</em></h2><p>Parkway approaches each enquiry as a manufacturing route—not a list of disconnected processes. Drawings, materials and downstream operations are considered together before production begins.</p></section><section class="services"><div class="section-head"><p class="eyebrow">Capabilities</p><h2>Built around<br><em>the requirement.</em></h2></div><div class="service-grid">${serviceLinks}</div></section>${workflow()}<section class="reviews"><p class="eyebrow">Google reviews</p><h2>Verified words only.</h2><div class="review-placeholder"><p>Review component ready for Parkway’s verified Google review text, reviewer names, dates and source link.</p><span>No rating or testimonial is published until its source is verified.</span></div></section>`});}

function workflow(){return `<section class="workflow"><div><p class="eyebrow">From drawing to delivery</p><h2>A clearer route<br><em>through production.</em></h2></div><ol><li><b>01</b><span>Drawing / CAD</span></li><li><b>02</b><span>Laser cutting</span></li><li><b>03</b><span>CNC folding</span></li><li><b>04</b><span>Welding / fabrication</span></li><li><b>05</b><span>Finish</span></li><li><b>06</b><span>Delivery</span></li></ol></section>`}

export function service(path){const s=services[path]; return layout({title:`${s.title} | Parkway Fabrications`,description:s.description,path,body:`<section class="page-hero"><p class="eyebrow">${s.eyebrow}</p><h1>${s.title}</h1><p class="lede">${s.description}</p><div class="actions"><a class="button" href="/request-a-quote/">Send a drawing</a><a class="text-link" href="${business.phoneHref}">Call ${business.phone} →</a></div></section><section class="editorial"><div><p class="eyebrow">A practical production route</p><h2>Scope first.<br><em>Then manufacture.</em></h2></div><div><p>${s.intro}</p><p>Capability, tolerances and acceptance remain subject to drawing review and written quotation. This keeps technical decisions tied to the actual component rather than unsupported headline claims.</p></div></section><section class="process"><p class="eyebrow">Process</p><h2>How an enquiry moves</h2><ol>${s.stages.map((x,i)=>`<li><span>0${i+1}</span><b>${x}</b></li>`).join('')}</ol></section><section class="faqs"><p class="eyebrow">Technical questions</p><h2>Before you send the enquiry</h2>${s.faq.map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('')}</section><section class="related"><h2>Connected services</h2><p><a href="/laser-cutting/">Laser cutting</a> · <a href="/cnc-folding/">CNC folding</a> · <a href="/welding/">Welding</a> · <a href="/metal-fabrication/">Metal fabrication</a></p></section>`});}

export function quote(){return layout({title:'Request a Quote | Parkway Fabrications Sheffield',description:'Send Parkway Fabrications your project details and engineering drawings for review.',path:'/request-a-quote/',body:`<section class="page-hero compact"><p class="eyebrow">Engineering enquiry</p><h1>Request a quote</h1><p class="lede">Give the team enough technical context to assess the route. Fields marked * are required.</p></section><form class="rfq" action="/api/rfq" method="post" enctype="multipart/form-data" data-rfq><div class="form-section"><p class="eyebrow">01 · Contact</p><div class="fields"><label>Name *<input name="name" autocomplete="name" required maxlength="100"></label><label>Company<input name="company" autocomplete="organization" maxlength="120"></label><label>Email *<input type="email" name="email" autocomplete="email" required maxlength="200"></label><label>Phone<input type="tel" name="phone" autocomplete="tel" maxlength="40"></label></div></div><div class="form-section"><p class="eyebrow">02 · Project</p><div class="fields"><label>Service *<select name="service" required><option value="">Choose a service</option>${Object.values(services).map(s=>`<option>${s.title.replace(' Sheffield','')}</option>`).join('')}</select></label><label>Material<input name="material" maxlength="80"></label><label>Thickness<input name="thickness" maxlength="40"></label><label>Quantity<input name="quantity" inputmode="numeric" maxlength="30"></label><label>Overall dimensions<input name="dimensions" maxlength="100"></label><label>Required-by date<input type="date" name="requiredBy"></label><label class="wide">Project description *<textarea name="description" rows="7" required maxlength="5000" placeholder="Describe the component, application, tolerances, finish and any downstream processes."></textarea></label></div></div><div class="form-section" id="upload"><p class="eyebrow">03 · Drawing</p><label class="drop">Upload engineering file<input type="file" name="drawing" accept=".dxf,.dwg,.step,.stp,.pdf,.svg,.jpg,.jpeg,.png"><span>DXF, DWG, STEP, STP, PDF, SVG, JPG or PNG · maximum 20MB</span></label><label class="honeypot" aria-hidden="true">Website<input name="website" tabindex="-1" autocomplete="off"></label><label class="consent"><input type="checkbox" name="consent" value="yes" required> I agree that Parkway may use these details to respond to this enquiry. *</label><button class="button" type="submit">Upload drawing & request quote</button><p role="status" aria-live="polite" data-status></p></div></form>`});}

export function simple(path){const pages={
 '/about/':['About Parkway Fabrications','Sheffield-based laser cutting and fabrication enquiries handled through a connected production workflow.',`<p>Parkway Fabrications operates from 4 Colwall Street, Sheffield. This preview deliberately avoids unverified history, workforce and accreditation claims while client fact-checking is completed.</p>${workflow()}`],
 '/contact/':['Contact Parkway Fabrications','Call, email or visit Parkway Fabrications in Sheffield.',`<div class="contact-grid"><address><b>Parkway Fabrications</b><br>${business.address.join('<br>')}</address><p><a href="${business.phoneHref}">${business.phone}</a><br><a href="mailto:${business.email}">${business.email}</a></p><p><a href="https://www.google.com/maps/search/?api=1&query=4%20Colwall%20Street%20Sheffield%20S9%203WP" rel="noopener">Get directions →</a></p></div>`],
 '/projects/':['Fabrication Projects','A case-study system ready for verified Parkway project details and photography.',`<div class="review-placeholder"><p>Project records are intentionally unpublished until Parkway supplies approved names, scope, imagery and outcomes.</p></div>`],
 '/privacy-policy/':['Privacy policy','How Parkway Fabrications handles website enquiries.',`<p>Enquiry information is used to assess and respond to your request. Uploaded drawings must be stored privately and accessed only by authorised staff. Production deployment requires Parkway’s approved retention period, data-controller details and processor agreements.</p><p>To ask about your data, email <a href="mailto:${business.email}">${business.email}</a>.</p>`],
 '/terms/':['Website terms','Terms for using the Parkway Fabrications website.',`<p>Website content is general information and does not form a manufacturing commitment. Capability, specification, price and delivery are confirmed only in Parkway’s written quotation. Final legal wording requires client approval before launch.</p>`]
}; const [title,description,content]=pages[path]; return layout({title:`${title} | Parkway Fabrications`,description,path,body:`<section class="page-hero compact"><p class="eyebrow">Parkway Fabrications</p><h1>${title}</h1><p class="lede">${description}</p></section><section class="legal">${content}</section>`});}

export function notFound(){return layout({title:'Page Not Found | Parkway Fabrications',description:'The requested page could not be found.',path:'/404/',body:`<section class="page-hero"><p class="eyebrow">404</p><h1>That route isn’t on the drawing.</h1><p class="lede">Return to Parkway’s capabilities or send the team your project requirements.</p><a class="button" href="/">Back to homepage</a></section>`});}
